pipelines:
  - PostgresToBigQuery:
      DisplayName: "Postgres To BigQuery Pipeline"
      Description: "Sample pipeline that reads data from a PostgreSQL database and writes it to BigQuery"
      Id: "pg2bq_1"
      DataSource:
        PostgreSQLSource:
          Host: "localhost"
          Port: 5432
          Database: "Postgres"
          Auth:
            BasicAuth:
              User: "admin"
              Password: "root"
          RawQuery: "SELECT user_id, order_id, order_date, item_price, item_id, item_quantity FROM order_items;"
      Transformations:
        - RenameColumn:
          - OldColumnName: "user_email"
            NewColumnName: "email"
        - WithColumn:
            Name: "item_total_price"
            Value: "item_price * item_quantity"
        - DropColumn: "item_quantity"
        - DropColumn: "item"
        - GroupBy:
            Columns:
              - "user_id"
            Aggregations:
              - Count
        - AddInsertTimestamp
      DataSink:
        BigQueryConfig:
          Project: "test-project"
          Dataset: "test-dataset"
          Table: "test-table"
          Auth:
            ServiceAccountAuth:
              ServiceAccountFile: "opt/shared/service_accounts/testing_service_accounts.json"
          AppendMode:
            Overwrite